id: P009277
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:31:14.247371
source_metadata:
  id: bdr:W1KG6199
  title: གསུང་འབུམ། འཇམ་དཔལ་དགྱེས་པའི་རྡོ་རྗེ།
  author: ''
  volumes:
    77155173f78c417a9794b17eaed9aa2e:
      image_group_id: I1KG6234
      title: ''
      volume_number: 1
      total_pages: 264
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
